#------------------------------------------------------------------------------
# FILE:         action.yaml
# CONTRIBUTOR:  Jeff Lill
# COPYRIGHT:    Copyright (c) 2005-2021 by neonFORGE LLC.  All rights reserved.
#
# The contents of this repository are for private use by neonFORGE, LLC. and may not be
# divulged or used for any purpose by other organizations or individuals without a
# formal written and signed agreement with neonFORGE, LLC

#------------------------------------------------------------------------------
# Sends a test related notification message to a Microsoft Teams channel URI.
#
# Each sending user sending messages will need a Teams channel URI for each channel
# being targeted.  This URI identifies the user by name and optionally a profile image
# and also includes a secret that authenticates the operation.  You can obtain channel
# URIs by following:
#
#   https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using
#
# Channel URIs are secrets and should be persisted to the 1Password account for the user
# and obtained at runtime via the noenFORGE deployment mechanisms.

name: teams-notify-test
description: "Sends a build related message to a Microsoft Teams channel URI"
inputs:
  channel:
    description: "Specifies the target Teams channel URI"
    required: true
  build-branch:
    description: "Optionally indicates which target repo branch was built"
    required: false
  build-config:
    description: "Optionally indicates the build/test configuration"
    required: false
  build-commit:
    description: "Optionally specifies the build commit"
    required: false
  build-commit-uri:
    description: "Optionally specifies target repo commit URI"
    required: false
  start-time:
    description: "Optionally indicates when the tests started (this must be formatted like: YYYY-MM-DD HH-MM:SSZ)"
    required: false
  finish-time:
    description: "Optionally indicates when the tests completed or failed"
    required: false
  test-summary:
    description: "Identifies the test being performed"
    required: true
  test-outcome:
    description: "Optionally specifies the build step outcome from [steps.BUILDSTEP.outcome], one of: 'success', 'failure', 'cancelled', or 'skipped'"
    required: true
  test-success:
    description: "The build step's [success] output"
    required: true
  test-filter:
    description: "Optionally specifies the test filter used"
    required: false
    default: ""
  test-result-uris:
    description: "Optionally specifies the list of semicolon separated markdown formatted URIs to the test results"
    required: false
  test-result-info:
    description: "Optionally specifies the list of semicolon separated test details formatted like: 'name,#tests,#errors,#skips,elapsed' corresponding to the [test-result-uris]."
    required: false
  test-issue-uri:
    description: "Optionally specifies the URI for the test failure issue or comment"
    required: false
  send-on:
    description: "Optionally specifies a space separated list of test outcomes that will trigger the notification or one of: `always`, `test-success`, or `test-fail"
    required: false
    default: always
runs:
  using: node12
  main: action.js
